---
# NOTE: _rts_quiet_assert does not impact this task, as it first needs to be ensured that it actually is
#       properly defined
- name: 'assert | Ensure boolean variables are defined properly'
  ansible.builtin.assert:
    that:
      - "lookup('ansible.builtin.vars', __t_var) is defined"
      - "lookup('ansible.builtin.vars', __t_var) | bool | string == lookup('ansible.builtin.vars', __t_var) | string"
      - "lookup('ansible.builtin.vars', __t_var) is boolean"
    success_msg: "Variable '{{ __t_var }}' defined properly - value: '{{ lookup('ansible.builtin.vars', __t_var) }}'"
    fail_msg: "Variable '{{ __t_var }}' failed to validate"
  loop:
    - '_rts_force_registration'
    - '_rts_quiet_assert'
    - '_rts_satellite_katello_ca_consumer_validate_certificates'
    - '_rts_satellite_validate_certificates'
  loop_control:
    loop_var: '__t_var'

- name: 'assert | Ensure string variables are defined properly'
  ansible.builtin.assert:
    that:
      - "lookup('ansible.builtin.vars', __t_var) is defined"
      - "lookup('ansible.builtin.vars', __t_var) is string"
      - "lookup('ansible.builtin.vars', __t_var) != None"
      - "lookup('ansible.builtin.vars', __t_var) != ''"
    success_msg: "Variable '{{ __t_var }}' defined properly - value: '{{ lookup('ansible.builtin.vars', __t_var) }}'"
    fail_msg: "Variable '{{ __t_var }}' failed to validate"
    quiet: '{{ _rts_quiet_assert }}'
  loop:
    - '_rts_katello_ca_consumer_regexp'
    - '_rts_rhsm_conf_path'
    - '_rts_satellite_katello_ca_consumer_package_name'
    - '_rts_satellite_katello_ca_consumer_published_path'
    - '_rts_satellite_katello_ca_consumer_scheme'
    - '_rts_satellite_activation_key'
    - '_rts_satellite_hostname'
    - '_rts_satellite_organization_name'
  loop_control:
    loop_var: '__t_var'

- name: 'assert | Ensure integer variables are defined properly'
  ansible.builtin.assert:
    that:
      - "lookup('ansible.builtin.vars', __t_var) is defined"
      - "lookup('ansible.builtin.vars', __t_var) | int | string == lookup('ansible.builtin.vars', __t_var) | string"
      - "lookup('ansible.builtin.vars', __t_var) | int is number"
      - "lookup('ansible.builtin.vars', __t_var) | int is integer"
      - "lookup('ansible.builtin.vars', __t_var) | int >= 0"
    success_msg: "Variable '{{ __t_var }}' defined properly - value: '{{ lookup('ansible.builtin.vars', __t_var) }}'"
    fail_msg: "Variable '{{ __t_var }}' failed to validate"
    quiet: '{{ _rts_quiet_assert }}'
  loop:
    - '_rts_satellite_katello_ca_consumer_port'
    - '_rts_satellite_port'
  loop_control:
    loop_var: '__t_var'
...
